using Microsoft.Win32;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
namespace SlideshowCreator;
public partial class MainWindow : Window
{
 public ObservableCollection<MediaItem> Media { get; }=new(); readonly SemaphoreSlim importGate=new(1,1); string? music; bool loadingSelection; bool seeking; bool previewPlaying; readonly Random rng=new(); string videoEncoder="libx264"; string videoPreset="medium";
 static readonly HashSet<string> VideoExt=new(StringComparer.OrdinalIgnoreCase){".mp4",".mov",".mkv",".avi",".m4v",".mts",".m2ts",".mpg",".mpeg",".wmv",".webm",".3gp",".ts",".vob",".mxf"};
 static readonly HashSet<string> PhotoExt=new(StringComparer.OrdinalIgnoreCase){".jpg",".jpeg",".png",".bmp",".tif",".tiff",".webp",".heic",".heif",".arw",".cr2",".cr3",".nef",".nrw",".orf",".rw2",".raf",".dng",".pef",".srw"};
 static readonly string[] Compositions={"2 Orizontal Opus","2 Orizontal Paralel","2 Orizontale Fluide","2 Orizontale Alternante","Diagonal / Opus","Diagonal \\ Opus","4 Cadrane → 1","4 → 2 → 1"};
 public MainWindow(){InitializeComponent();DataContext=this;DetectEncoder();}
 void DetectEncoder(){try{var s=Run("ffmpeg.exe","-hide_banner -encoders",out var code);if(code==0&&s.Contains("h264_nvenc")){var test=Path.Combine(Path.GetTempPath(),"sc_nvenc_test.mp4");Run("ffmpeg.exe",$"-y -f lavfi -i color=c=black:s=320x180:d=0.15 -an -c:v h264_nvenc -preset p4 \"{test}\"",out var nc);try{File.Delete(test);}catch{}if(nc==0){videoEncoder="h264_nvenc";videoPreset="p4";DetailStatusText.Text="0.1.11 • NVIDIA NVENC verificat • motor direct";return;}}videoEncoder="libx264";videoPreset="veryfast";DetailStatusText.Text="0.1.11 • CPU x264 fallback • motor direct";}catch{videoEncoder="libx264";videoPreset="veryfast";DetailStatusText.Text="0.1.10 • CPU x264 fallback";}}
 async void AddMedia_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Multiselect=true,Filter="Foto / RAW / video|*.jpg;*.jpeg;*.png;*.bmp;*.tif;*.tiff;*.webp;*.heic;*.heif;*.arw;*.cr2;*.cr3;*.nef;*.nrw;*.orf;*.rw2;*.raf;*.dng;*.pef;*.srw;*.mp4;*.mov;*.mkv;*.avi;*.m4v;*.mts;*.m2ts;*.mpg;*.mpeg;*.wmv;*.webm;*.3gp;*.ts;*.vob;*.mxf|Toate fișierele|*.*"};if(d.ShowDialog()==true)await ImportFilesAsync(d.FileNames);}
 async Task ImportFilesAsync(IEnumerable<string> paths){await importGate.WaitAsync();try{ImportDropZone.Visibility=Visibility.Collapsed;var batch=paths.Where(File.Exists).ToArray();int added=0;foreach(var p in batch){var ext=Path.GetExtension(p);bool video=VideoExt.Contains(ext),photo=PhotoExt.Contains(ext);if(!video&&!photo)continue;var sourceDur=video?await Task.Run(()=>Probe(p)):4;var item=new MediaItem{Path=p,Type=video?"Video":"Foto",Date=File.GetLastWriteTime(p),Duration=sourceDur,SourceDuration=sourceDur};item.Thumbnail=await Task.Run(()=>video?CreateVideoThumb(p):LoadPhotoThumb(p));Media.Add(item);added++;CountText.Text=$"{Media.Count} elemente";}StatusText.Text=$"Import adăugat: +{added}. Total păstrat în proiect: {Media.Count} elemente.";}finally{if(Media.Count==0)ImportDropZone.Visibility=Visibility.Visible;importGate.Release();}}
 static double Probe(string p){try{var s=Run("ffprobe.exe",$"-v error -show_entries format=duration -of default=nw=1:nk=1 \"{p}\"",out var c);if(c==0&&double.TryParse(s.Trim(),NumberStyles.Float,CultureInfo.InvariantCulture,out var n))return Math.Max(.1,n);}catch{}return 5;}
 static ImageSource? LoadPhotoThumb(string p){try{var b=new BitmapImage();b.BeginInit();b.CacheOption=BitmapCacheOption.OnLoad;b.DecodePixelWidth=240;b.UriSource=new Uri(p);b.EndInit();b.Freeze();return b;}catch{return null;}}
 static ImageSource? CreateVideoThumb(string p){try{var dir=Path.Combine(Path.GetTempPath(),"SlideshowCreatorThumbs");Directory.CreateDirectory(dir);var jpg=Path.Combine(dir,Math.Abs(p.GetHashCode())+".jpg");if(!File.Exists(jpg))Run("ffmpeg.exe",$"-y -ss 0.5 -i \"{p}\" -frames:v 1 -vf \"scale=240:-2:force_original_aspect_ratio=decrease\" -q:v 3 \"{jpg}\"",out _);if(!File.Exists(jpg))return null;var b=new BitmapImage();b.BeginInit();b.CacheOption=BitmapCacheOption.OnLoad;b.UriSource=new Uri(jpg);b.EndInit();b.Freeze();return b;}catch{return null;}}
 void AddMusic_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Audio|*.mp3;*.wav;*.m4a;*.aac;*.flac;*.ogg;*.opus|Toate fișierele|*.*"};if(d.ShowDialog()==true){music=d.FileName;MusicLabel.Text="Muzică: "+Path.GetFileName(music);}}
 void Sort_Click(object s,RoutedEventArgs e){var a=Media.OrderBy(x=>x.Date).ToList();Media.Clear();foreach(var x in a)Media.Add(x);StatusText.Text="Sortare cronologică terminată";}
 void Remove_Click(object s,RoutedEventArgs e){if(MediaList.SelectedItem is MediaItem m)Media.Remove(m);CountText.Text=$"{Media.Count} elemente";if(Media.Count==0)ImportDropZone.Visibility=Visibility.Visible;}
 void MediaList_SelectionChanged(object s,SelectionChangedEventArgs e){if(MediaList.SelectedItem is not MediaItem m)return;loadingSelection=true;DurationBox.Text=F(m.Duration);TrimInBox.Text=F(m.TrimIn);TrimOutBox.Text=F(m.TrimOut);MuteBox.IsChecked=m.Mute;TransitionDurationBox.Text=F(m.TransitionDuration);SelectCombo(TransitionBox,m.Transition);SelectCombo(CompositionBox,m.Composition);loadingSelection=false;VideoPreview.Stop();VideoPreview.Visibility=Visibility.Collapsed;VideoControls.Visibility=Visibility.Collapsed;PhotoPreview.Visibility=Visibility.Collapsed;if(m.Type=="Foto"){try{PhotoPreview.Source=new BitmapImage(new Uri(m.Path));}catch{PhotoPreview.Source=m.Thumbnail;}PhotoPreview.Visibility=Visibility.Visible;}else try{VideoPreview.Source=new Uri(m.Path);VideoPreview.Visibility=Visibility.Visible;VideoControls.Visibility=Visibility.Visible;VideoSeek.Maximum=Math.Max(.1,m.SourceDuration);VideoSeek.Value=m.TrimIn;VideoTimeText.Text=$"{F(m.TrimIn)} / {F(m.SourceDuration)} s";}catch{}}
 static void SelectCombo(ComboBox box,string value){foreach(var x in box.Items.OfType<ComboBoxItem>())if((x.Content?.ToString()??"")==value){box.SelectedItem=x;return;}}
 void Property_Changed(object s,RoutedEventArgs e){if(MediaList.SelectedItem is not MediaItem m)return;if(double.TryParse(DurationBox.Text.Replace(',','.'),NumberStyles.Float,CultureInfo.InvariantCulture,out var d))m.Duration=Math.Max(.1,d);if(double.TryParse(TrimInBox.Text.Replace(',','.'),NumberStyles.Float,CultureInfo.InvariantCulture,out var t))m.TrimIn=Math.Clamp(t,0,Math.Max(0,m.SourceDuration-.1));m.Duration=Math.Min(m.Duration,Math.Max(.1,m.SourceDuration-m.TrimIn));TrimOutBox.Text=F(m.TrimOut);m.Mute=MuteBox.IsChecked==true;m.Changed(nameof(MediaItem.Duration));}

 void TrimOut_Changed(object s,RoutedEventArgs e){if(MediaList.SelectedItem is not MediaItem m||m.Type!="Video")return;if(double.TryParse(TrimOutBox.Text.Replace(',','.'),NumberStyles.Float,CultureInfo.InvariantCulture,out var t)){t=Math.Clamp(t,m.TrimIn+.1,m.SourceDuration);m.Duration=t-m.TrimIn;DurationBox.Text=F(m.Duration);m.Changed(nameof(MediaItem.Duration));}}
 void VideoPreview_MediaOpened(object s,RoutedEventArgs e){if(MediaList.SelectedItem is not MediaItem m)return;if(VideoPreview.NaturalDuration.HasTimeSpan){m.SourceDuration=VideoPreview.NaturalDuration.TimeSpan.TotalSeconds;VideoSeek.Maximum=m.SourceDuration;TrimOutBox.Text=F(m.TrimOut);}VideoPreview.Position=TimeSpan.FromSeconds(m.TrimIn);}
 void VideoSeek_ValueChanged(object s,RoutedPropertyChangedEventArgs<double> e){if(loadingSelection||seeking||VideoPreview?.Source==null)return;seeking=true;try{VideoPreview.Position=TimeSpan.FromSeconds(VideoSeek.Value);VideoTimeText.Text=$"{F(VideoSeek.Value)} / {F(VideoSeek.Maximum)} s";}finally{seeking=false;}}
 void PreviewPlayPause_Click(object s,RoutedEventArgs e){if(VideoPreview.Source==null)return;if(previewPlaying){VideoPreview.Pause();previewPlaying=false;}else{VideoPreview.Play();previewPlaying=true;}}
 void SetTrimIn_Click(object s,RoutedEventArgs e){if(MediaList.SelectedItem is not MediaItem m||m.Type!="Video")return;var oldOut=m.TrimOut;m.TrimIn=Math.Clamp(VideoPreview.Position.TotalSeconds,0,Math.Max(0,m.SourceDuration-.1));m.Duration=Math.Max(.1,oldOut-m.TrimIn);TrimInBox.Text=F(m.TrimIn);TrimOutBox.Text=F(m.TrimOut);DurationBox.Text=F(m.Duration);}
 void SetTrimOut_Click(object s,RoutedEventArgs e){if(MediaList.SelectedItem is not MediaItem m||m.Type!="Video")return;var o=Math.Clamp(VideoPreview.Position.TotalSeconds,m.TrimIn+.1,m.SourceDuration);m.Duration=o-m.TrimIn;TrimOutBox.Text=F(o);DurationBox.Text=F(m.Duration);}
 void Transition_Changed(object s,RoutedEventArgs e){if(loadingSelection||MediaList?.SelectedItem is not MediaItem m||TransitionBox==null||TransitionDurationBox==null)return;m.Transition=(TransitionBox.SelectedItem as ComboBoxItem)?.Content?.ToString()??"Crossfade";if(double.TryParse(TransitionDurationBox.Text.Replace(',','.'),NumberStyles.Float,CultureInfo.InvariantCulture,out var td))m.TransitionDuration=td;}
 void MixTransitions_Click(object s,RoutedEventArgs e){if(Media.Count<2){StatusText.Text="Sunt necesare cel puțin 2 cadre.";return;}var mode=(MixModeBox.SelectedItem as ComboBoxItem)?.Content?.ToString()??"Elegant";string[] pool=mode switch{"Alternativ"=>new[]{"Crossfade","Slide Stânga","Crossfade","Slide Dreapta","Dissolve","Wipe Stânga","Dissolve","Wipe Dreapta"},"Dinamic"=>new[]{"Slide Stânga","Wipe Dreapta","Diagonal TL","Dissolve","Slide Dreapta","Wipe Sus","Diagonal BR","Crossfade","Wipe Stânga","Diagonal TR"},_=>new[]{"Crossfade","Dissolve","Slide Stânga","Crossfade","Wipe Dreapta","Dissolve","Slide Dreapta","Crossfade","Wipe Stânga"}};for(int i=0;i<Media.Count;i++){Media[i].Transition=pool[i%pool.Length];Media[i].TransitionDuration=mode=="Dinamic"?.55:.7;}StatusText.Text=$"Mix tranziții {mode} aplicat";}
 void Composition_Changed(object s,SelectionChangedEventArgs e){if(loadingSelection||MediaList?.SelectedItem is not MediaItem)return;StatusText.Text="CARUSEL ales. Apasă APLICĂ MANUAL pentru a o fixa pe segment.";}
 void CompositionManual_Click(object s,RoutedEventArgs e){if(MediaList.SelectedItem is not MediaItem m)return;var idx=Media.IndexOf(m);var c=(CompositionBox.SelectedItem as ComboBoxItem)?.Content?.ToString()??"Full Frame";if((c=="4 Cadrane → 1"||c=="4 → 2 → 1")&&idx>Media.Count-4){StatusText.Text="CARUSELUL 4 Cadrane → 1 are nevoie de 4 elemente consecutive.";return;}if(c!="Full Frame"&&c!="4 Cadrane → 1"&&c!="4 → 2 → 1"&&idx>=Media.Count-1){StatusText.Text="CARUSELUL pe 2 planuri are nevoie de încă un element după segmentul selectat.";return;}m.Composition=c;m.CompositionManual=true;StatusText.Text=$"Manual: {c} pe segmentul {idx+1}";}
 void RandomCompositions_Click(object s,RoutedEventArgs e){if(Media.Count<3){StatusText.Text="Pentru CARUSEL Automat sunt necesare cel puțin 3 cadre.";return;}foreach(var m in Media.Where(x=>!x.CompositionManual))m.Composition="Full Frame";int applied=0;for(int i=0;i<Media.Count;){if(Media[i].CompositionManual){i++;continue;}var remain=Media.Count-i;if(remain>=8&&(i==0||i%24==0)){Media[i].Composition="CARUSEL AUTOMAT";Media[i].CompositionManual=false;applied++;i+=Math.Min(remain,12);continue;}if(remain>=4&&rng.NextDouble()<.34){Media[i].Composition=rng.Next(2)==0?"4 Cadrane → 1":"4 → 2 → 1";Media[i].CompositionManual=false;applied++;i+=4;continue;}if(remain>=2&&rng.NextDouble()<.48){var pool=Compositions.Where(x=>x!="4 Cadrane → 1"&&x!="4 → 2 → 1").ToArray();Media[i].Composition=pool[rng.Next(pool.Length)];Media[i].CompositionManual=false;applied++;i+=2;continue;}i++;}StatusText.Text=$"CARUSEL Automat Engine 2: {applied} secvențe; include accente WALL/Heart/Burst/Train și păstrează intervențiile manuale.";}
 void ClearCompositions_Click(object s,RoutedEventArgs e){foreach(var m in Media){m.Composition="Full Frame";m.CompositionManual=false;}StatusText.Text="CARUSEL resetat la Full Frame.";}
 async void PreviewMontage_Click(object s,RoutedEventArgs e){if(Media.Count==0){MessageBox.Show("Importă mai întâi materialele.");return;}var dir=Path.Combine(Path.GetTempPath(),"SlideshowCreatorPreview");Directory.CreateDirectory(dir);var p=Path.Combine(dir,"preview.mp4");try{IsEnabled=false;ExportProgress.Visibility=Visibility.Visible;StatusText.Text="PREVIEW rapid — construiesc montajul la rezoluție redusă...";await Task.Run(()=>ExportPreview(p));VideoPreview.Stop();PhotoPreview.Visibility=Visibility.Collapsed;ImportDropZone.Visibility=Visibility.Collapsed;VideoPreview.Source=new Uri(p);VideoPreview.Visibility=Visibility.Visible;VideoControls.Visibility=Visibility.Visible;VideoSeek.Minimum=0;VideoSeek.Maximum=Math.Max(.1,Probe(p));VideoSeek.Value=0;VideoPreview.Position=TimeSpan.Zero;VideoPreview.Play();previewPlaying=true;StatusText.Text="PREVIEW MONTAJ — redare rapidă, exportul final rămâne Full HD.";}catch(Exception ex){MessageBox.Show(ex.Message,"Eroare preview");}finally{IsEnabled=true;ExportProgress.Visibility=Visibility.Collapsed;}}
 void ExportPreview(string dest){string oldEncoder=videoEncoder,oldPreset=videoPreset;try{videoEncoder="libx264";videoPreset="ultrafast";ExportInternal(dest,true,null);}finally{videoEncoder=oldEncoder;videoPreset=oldPreset;}}
 void Preview_Click(object s,RoutedEventArgs e){if(MediaList.SelectedItem is MediaItem m&&m.Type=="Video")try{VideoPreview.Position=TimeSpan.FromSeconds(m.TrimIn);VideoPreview.Play();}catch{}}
 async void Export_Click(object s,RoutedEventArgs e){if(Media.Count==0){MessageBox.Show("Importă mai întâi materialele.");return;}var d=new SaveFileDialog{Filter="Video MP4|*.mp4",FileName="Slideshow-0.1.11.mp4",AddExtension=true,DefaultExt=".mp4"};if(d.ShowDialog()!=true)return;try{IsEnabled=false;ExportProgress.Visibility=Visibility.Visible;StatusText.Text="Export 0.1.11 — motor direct din originale...";await Task.Run(()=>Export(d.FileName));StatusText.Text="Export finalizat";System.Media.SystemSounds.Asterisk.Play();MessageBox.Show("Export MP4 0.1.11 finalizat.\n\n"+d.FileName,"Slideshow Creator 0.1.11");}catch(Exception ex){MessageBox.Show(ex.Message,"Eroare export");}finally{IsEnabled=true;ExportProgress.Visibility=Visibility.Collapsed;}}
 void Export(string dest)=>DirectExportEngine.Export(Media.ToList(),dest,music,videoEncoder,videoPreset,Ffmpeg,Probe,(pct,msg)=>Dispatcher.Invoke(()=>{ExportProgress.Value=pct;StatusText.Text=msg;}));
 void ExportInternal(string dest,bool preview,Action<double,string>? progress=null){var dir=Path.Combine(Path.GetTempPath(),"SlideshowCreator",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);try{var normalized=new List<MediaItem>();int n=0;int totalItems=Media.Count;foreach(var m in Media){progress?.Invoke(5+55.0*n/Math.Max(1,totalItems),$"Pregătire cadre: {n+1} / {totalItems}");var c=Path.Combine(dir,$"n{n++:0000}.mp4");Normalize(m,c,preview);normalized.Add(new MediaItem{Path=c,Type="Video",Duration=m.Duration,Transition=m.Transition,TransitionDuration=m.TransitionDuration,Composition=m.Composition,CompositionManual=m.CompositionManual});}
 progress?.Invoke(60,"Construiesc CARUSEL-urile și compozițiile..."); var sequence=new List<MediaItem>();for(int i=0;i<normalized.Count;i++){var m=normalized[i];if((m.Composition=="4 Cadrane → 1"||m.Composition=="4 → 2 → 1")&&i+3<normalized.Count){var outc=Path.Combine(dir,$"carousel4_{i:0000}.mp4");var dur=Math.Max(4.2,new[]{normalized[i].Duration,normalized[i+1].Duration,normalized[i+2].Duration,normalized[i+3].Duration}.Min());var graph=m.Composition=="4 → 2 → 1"?CompositionRenderEngine.BuildFourToTwoToOne(dur):CompositionRenderEngine.BuildFourToOne(dur);Ffmpeg($"-y -i \"{normalized[i].Path}\" -i \"{normalized[i+1].Path}\" -i \"{normalized[i+2].Path}\" -i \"{normalized[i+3].Path}\" -filter_complex \"{graph}\" -map \"[outv]\" -an -c:v {videoEncoder} -preset {videoPreset} -pix_fmt yuv420p \"{outc}\"");sequence.Add(new MediaItem{Path=outc,Type="Video",Duration=dur,Transition=m.Transition,TransitionDuration=m.TransitionDuration});i+=3;}else if(m.Composition!="Full Frame"&&i+1<normalized.Count){var second=normalized[i+1];var outc=Path.Combine(dir,$"comp{i:0000}.mp4");var dur=Math.Max(1.2,Math.Min(m.Duration,second.Duration));var graph=CompositionRenderEngine.BuildTwoPlan(m.Composition,dur);Ffmpeg($"-y -i \"{m.Path}\" -i \"{second.Path}\" -filter_complex \"{graph}\" -map \"[outv]\" -an -c:v {videoEncoder} -preset {videoPreset} -pix_fmt yuv420p \"{outc}\"");sequence.Add(new MediaItem{Path=outc,Type="Video",Duration=dur,Transition=m.Transition,TransitionDuration=m.TransitionDuration});i++;}else sequence.Add(m);}
 progress?.Invoke(72,"Randare montaj principal..."); var visual=Path.Combine(dir,"visual_raw.mp4");if(sequence.Count==1)File.Copy(sequence[0].Path,visual,true);else{var inputs=string.Join(" ",sequence.Select(x=>$"-i \"{x.Path}\""));var graph=SlideshowRenderEngine.BuildPhotoFilter(sequence);Ffmpeg($"-y {inputs} -filter_complex \"{graph}\" -map \"[outv]\" -an -c:v {videoEncoder} -preset {videoPreset} -pix_fmt yuv420p \"{visual}\"");}progress?.Invoke(88,"Finalizare imagine și intro/outro...");var total=Probe(visual);var intro=Math.Min(1.25,Math.Max(.25,total*.12));var outro=Math.Min(1.8,Math.Max(.35,total*.15));var outStart=Math.Max(intro,total-outro);if(music==null){progress?.Invoke(92,"Finalizare imagine...");Ffmpeg($"-y -i \"{visual}\" -vf \"fade=t=in:st=0:d={F(intro)},fade=t=out:st={F(outStart)}:d={F(outro)}\" -an -c:v {videoEncoder} -preset {videoPreset} -pix_fmt yuv420p -movflags +faststart \"{dest}\"");progress?.Invoke(100,"Export finalizat");}else {progress?.Invoke(92,"Finalizare imagine + muzică într-o singură trecere...");Ffmpeg($"-y -i \"{visual}\" -stream_loop -1 -i \"{music}\" -vf \"fade=t=in:st=0:d={F(intro)},fade=t=out:st={F(outStart)}:d={F(outro)}\" -filter:a \"afade=t=in:st=0:d={F(intro)},afade=t=out:st={F(outStart)}:d={F(outro)}\" -map 0:v -map 1:a -c:v {videoEncoder} -preset {videoPreset} -pix_fmt yuv420p -c:a aac -b:a 256k -t {F(total)} -movflags +faststart \"{dest}\"");progress?.Invoke(100,"Export finalizat");}}finally{try{Directory.Delete(dir,true);}catch{}}}
 void Normalize(MediaItem m,string c,bool preview=false){var vf=preview?"scale=960:540:force_original_aspect_ratio=decrease,pad=960:540:(ow-iw)/2:(oh-ih)/2:black,fps=24,scale=1920:1080,format=yuv420p":"scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black,fps=30,format=yuv420p";var enc=preview?"libx264":videoEncoder;var preset=preview?"ultrafast":videoPreset;if(m.Type=="Foto")Ffmpeg($"-y -loop 1 -t {F(m.Duration)} -i \"{m.Path}\" -vf \"{vf}\" -an -c:v {enc} -preset {preset} \"{c}\"");else Ffmpeg($"-y -ss {F(m.TrimIn)} -i \"{m.Path}\" -t {F(m.Duration)} -vf \"{vf}\" -an -c:v {enc} -preset {preset} \"{c}\"");}
 static string F(double n){var s=n.ToString("0.###",CultureInfo.InvariantCulture);return s.StartsWith(".")?"0"+s:s.StartsWith("-.")?"-0"+s[1..]:s;}
 static void Ffmpeg(string args){var t=Run("ffmpeg.exe",args,out var c);if(c!=0)throw new Exception("FFmpeg a oprit exportul.\n\n"+(t.Length>1800?t[^1800..]:t));}
 static string Run(string exe,string args,out int code){var path=Path.Combine(AppContext.BaseDirectory,"Tools",exe);if(!File.Exists(path))throw new FileNotFoundException("Lipsește "+exe,path);using var p=new Process();p.StartInfo=new ProcessStartInfo(path,args){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};var sb=new StringBuilder();p.OutputDataReceived+=(_,e)=>{if(e.Data!=null)lock(sb)sb.AppendLine(e.Data);};p.ErrorDataReceived+=(_,e)=>{if(e.Data!=null)lock(sb)sb.AppendLine(e.Data);};p.Start();p.BeginOutputReadLine();p.BeginErrorReadLine();p.WaitForExit();code=p.ExitCode;lock(sb)return sb.ToString();}
 void Window_PreviewDragOver(object s,DragEventArgs e){e.Effects=e.Data.GetDataPresent(DataFormats.FileDrop)?DragDropEffects.Copy:DragDropEffects.None;e.Handled=true;}async void Window_Drop(object s,DragEventArgs e){if(e.Data.GetData(DataFormats.FileDrop)is string[] files)await ImportFilesAsync(files);}
}