using Microsoft.Win32;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
namespace SlideshowCreator;
public partial class MainWindow : Window
{
 public ObservableCollection<MediaItem> Media { get; }=new(); string? music; bool loadingSelection; readonly Random rng=new();
 static readonly HashSet<string> VideoExt=new(StringComparer.OrdinalIgnoreCase){".mp4",".mov",".mkv",".avi",".m4v",".mts",".m2ts",".mpg",".mpeg",".wmv",".webm",".3gp",".ts",".vob",".mxf"};
 static readonly HashSet<string> PhotoExt=new(StringComparer.OrdinalIgnoreCase){".jpg",".jpeg",".png",".bmp",".tif",".tiff",".webp",".heic",".heif",".arw",".cr2",".cr3",".nef",".nrw",".orf",".rw2",".raf",".dng",".pef",".srw"};
 static readonly string[] Compositions={"2 Orizontal Opus","2 Orizontal Paralel","2 Orizontale Fluide","Diagonal / Opus","Diagonal \\ Opus","4 Cadrane → 1"};
 public MainWindow(){InitializeComponent();DataContext=this;}
 async void AddMedia_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Multiselect=true,Filter="Foto / RAW / video|*.jpg;*.jpeg;*.png;*.bmp;*.tif;*.tiff;*.webp;*.heic;*.heif;*.arw;*.cr2;*.cr3;*.nef;*.nrw;*.orf;*.rw2;*.raf;*.dng;*.pef;*.srw;*.mp4;*.mov;*.mkv;*.avi;*.m4v;*.mts;*.m2ts;*.mpg;*.mpeg;*.wmv;*.webm;*.3gp;*.ts;*.vob;*.mxf|Toate fișierele|*.*"};if(d.ShowDialog()==true)await ImportFilesAsync(d.FileNames);}
 async Task ImportFilesAsync(IEnumerable<string> paths){ImportDropZone.Visibility=Visibility.Collapsed;foreach(var p in paths.Where(File.Exists)){var ext=Path.GetExtension(p);bool video=VideoExt.Contains(ext),photo=PhotoExt.Contains(ext);if(!video&&!photo)continue;var item=new MediaItem{Path=p,Type=video?"Video":"Foto",Date=File.GetLastWriteTime(p),Duration=video?await Task.Run(()=>Probe(p)):4};item.Thumbnail=await Task.Run(()=>video?CreateVideoThumb(p):LoadPhotoThumb(p));Media.Add(item);CountText.Text=$"{Media.Count} elemente";}StatusText.Text=$"Import finalizat: {Media.Count} elemente";if(Media.Count==0)ImportDropZone.Visibility=Visibility.Visible;}
 static double Probe(string p){try{var s=Run("ffprobe.exe",$"-v error -show_entries format=duration -of default=nw=1:nk=1 \"{p}\"",out var c);if(c==0&&double.TryParse(s.Trim(),NumberStyles.Float,CultureInfo.InvariantCulture,out var n))return Math.Max(.1,n);}catch{}return 5;}
 static ImageSource? LoadPhotoThumb(string p){try{var b=new BitmapImage();b.BeginInit();b.CacheOption=BitmapCacheOption.OnLoad;b.DecodePixelWidth=240;b.UriSource=new Uri(p);b.EndInit();b.Freeze();return b;}catch{return null;}}
 static ImageSource? CreateVideoThumb(string p){try{var dir=Path.Combine(Path.GetTempPath(),"SlideshowCreatorThumbs");Directory.CreateDirectory(dir);var jpg=Path.Combine(dir,Math.Abs(p.GetHashCode())+".jpg");if(!File.Exists(jpg))Run("ffmpeg.exe",$"-y -ss 0.5 -i \"{p}\" -frames:v 1 -vf \"scale=240:-2:force_original_aspect_ratio=decrease\" -q:v 3 \"{jpg}\"",out _);if(!File.Exists(jpg))return null;var b=new BitmapImage();b.BeginInit();b.CacheOption=BitmapCacheOption.OnLoad;b.UriSource=new Uri(jpg);b.EndInit();b.Freeze();return b;}catch{return null;}}
 void AddMusic_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Audio|*.mp3;*.wav;*.m4a;*.aac;*.flac;*.ogg;*.opus|Toate fișierele|*.*"};if(d.ShowDialog()==true){music=d.FileName;MusicLabel.Text="Muzică: "+Path.GetFileName(music);}}
 void Sort_Click(object s,RoutedEventArgs e){var a=Media.OrderBy(x=>x.Date).ToList();Media.Clear();foreach(var x in a)Media.Add(x);StatusText.Text="Sortare cronologică terminată";}
 void Remove_Click(object s,RoutedEventArgs e){if(MediaList.SelectedItem is MediaItem m)Media.Remove(m);CountText.Text=$"{Media.Count} elemente";if(Media.Count==0)ImportDropZone.Visibility=Visibility.Visible;}
 void MediaList_SelectionChanged(object s,SelectionChangedEventArgs e){if(MediaList.SelectedItem is not MediaItem m)return;loadingSelection=true;DurationBox.Text=F(m.Duration);TrimInBox.Text=F(m.TrimIn);MuteBox.IsChecked=m.Mute;TransitionDurationBox.Text=F(m.TransitionDuration);SelectCombo(TransitionBox,m.Transition);SelectCombo(CompositionBox,m.Composition);loadingSelection=false;VideoPreview.Stop();VideoPreview.Visibility=Visibility.Collapsed;PhotoPreview.Visibility=Visibility.Collapsed;if(m.Type=="Foto"){try{PhotoPreview.Source=new BitmapImage(new Uri(m.Path));}catch{PhotoPreview.Source=m.Thumbnail;}PhotoPreview.Visibility=Visibility.Visible;}else try{VideoPreview.Source=new Uri(m.Path);VideoPreview.Visibility=Visibility.Visible;}catch{}}
 static void SelectCombo(ComboBox box,string value){foreach(var x in box.Items.OfType<ComboBoxItem>())if((x.Content?.ToString()??"")==value){box.SelectedItem=x;return;}}
 void Property_Changed(object s,RoutedEventArgs e){if(MediaList.SelectedItem is not MediaItem m)return;if(double.TryParse(DurationBox.Text.Replace(',','.'),NumberStyles.Float,CultureInfo.InvariantCulture,out var d))m.Duration=Math.Max(.1,d);if(double.TryParse(TrimInBox.Text.Replace(',','.'),NumberStyles.Float,CultureInfo.InvariantCulture,out var t))m.TrimIn=Math.Max(0,t);m.Mute=MuteBox.IsChecked==true;m.Changed(nameof(MediaItem.Duration));}
 void Transition_Changed(object s,RoutedEventArgs e){if(loadingSelection||MediaList?.SelectedItem is not MediaItem m||TransitionBox==null||TransitionDurationBox==null)return;m.Transition=(TransitionBox.SelectedItem as ComboBoxItem)?.Content?.ToString()??"Crossfade";if(double.TryParse(TransitionDurationBox.Text.Replace(',','.'),NumberStyles.Float,CultureInfo.InvariantCulture,out var td))m.TransitionDuration=td;}
 void MixTransitions_Click(object s,RoutedEventArgs e){if(Media.Count<2){StatusText.Text="Sunt necesare cel puțin 2 cadre.";return;}var mode=(MixModeBox.SelectedItem as ComboBoxItem)?.Content?.ToString()??"Elegant";string[] pool=mode switch{"Alternativ"=>new[]{"Crossfade","Slide Stânga","Crossfade","Slide Dreapta","Dissolve","Wipe Stânga","Dissolve","Wipe Dreapta"},"Dinamic"=>new[]{"Slide Stânga","Wipe Dreapta","Diagonal TL","Dissolve","Slide Dreapta","Wipe Sus","Diagonal BR","Crossfade","Wipe Stânga","Diagonal TR"},_=>new[]{"Crossfade","Dissolve","Slide Stânga","Crossfade","Wipe Dreapta","Dissolve","Slide Dreapta","Crossfade","Wipe Stânga"}};for(int i=0;i<Media.Count;i++){Media[i].Transition=pool[i%pool.Length];Media[i].TransitionDuration=mode=="Dinamic"?.55:.7;}StatusText.Text=$"Mix tranziții {mode} aplicat";}
 void Composition_Changed(object s,SelectionChangedEventArgs e){if(loadingSelection||MediaList?.SelectedItem is not MediaItem)return;StatusText.Text="CARUSEL ales. Apasă APLICĂ MANUAL pentru a o fixa pe segment.";}
 void CompositionManual_Click(object s,RoutedEventArgs e){if(MediaList.SelectedItem is not MediaItem m)return;var idx=Media.IndexOf(m);var c=(CompositionBox.SelectedItem as ComboBoxItem)?.Content?.ToString()??"Full Frame";if(c=="4 Cadrane → 1"&&idx>Media.Count-4){StatusText.Text="CARUSELUL 4 Cadrane → 1 are nevoie de 4 elemente consecutive.";return;}if(c!="Full Frame"&&c!="4 Cadrane → 1"&&idx>=Media.Count-1){StatusText.Text="CARUSELUL pe 2 planuri are nevoie de încă un element după segmentul selectat.";return;}m.Composition=c;m.CompositionManual=true;StatusText.Text=$"Manual: {c} pe segmentul {idx+1}";}
 void RandomCompositions_Click(object s,RoutedEventArgs e){if(Media.Count<3){StatusText.Text="Pentru CARUSEL Automat sunt necesare cel puțin 3 cadre.";return;}foreach(var m in Media.Where(x=>!x.CompositionManual))m.Composition="Full Frame";string? last=null;int applied=0;for(int i=1;i<Media.Count-1;i+=3){if(Media[i].CompositionManual)continue;var choices=Compositions.Where(x=>x!=last).ToArray();var c=choices[rng.Next(choices.Length)];Media[i].Composition=c;Media[i].CompositionManual=false;last=c;applied++;}StatusText.Text=$"Random controlat: {applied} secvențe CARUSEL, fără repetare consecutivă; alegerile manuale au fost păstrate.";}
 void ClearCompositions_Click(object s,RoutedEventArgs e){foreach(var m in Media){m.Composition="Full Frame";m.CompositionManual=false;}StatusText.Text="CARUSEL resetat la Full Frame.";}
 void Preview_Click(object s,RoutedEventArgs e){if(MediaList.SelectedItem is MediaItem m&&m.Type=="Video")try{VideoPreview.Position=TimeSpan.FromSeconds(m.TrimIn);VideoPreview.Play();}catch{}}
 async void Export_Click(object s,RoutedEventArgs e){if(Media.Count==0){MessageBox.Show("Importă mai întâi materialele.");return;}var d=new SaveFileDialog{Filter="Video MP4|*.mp4",FileName="Slideshow-0.1.9.mp4",AddExtension=true,DefaultExt=".mp4"};if(d.ShowDialog()!=true)return;try{IsEnabled=false;ExportProgress.Visibility=Visibility.Visible;StatusText.Text="Export 0.1.9 — pregătire cadre și compoziții...";await Task.Run(()=>Export(d.FileName));StatusText.Text="Export finalizat";MessageBox.Show("Export MP4 0.1.9 finalizat.\n\n"+d.FileName,"Slideshow Creator 0.1.9");}catch(Exception ex){MessageBox.Show(ex.Message,"Eroare export");}finally{IsEnabled=true;ExportProgress.Visibility=Visibility.Collapsed;}}
 void Export(string dest){var dir=Path.Combine(Path.GetTempPath(),"SlideshowCreator",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);try{var normalized=new List<MediaItem>();int n=0;foreach(var m in Media){var c=Path.Combine(dir,$"n{n++:0000}.mp4");Normalize(m,c);normalized.Add(new MediaItem{Path=c,Type="Video",Duration=m.Duration,Transition=m.Transition,TransitionDuration=m.TransitionDuration,Composition=m.Composition,CompositionManual=m.CompositionManual});}
 var sequence=new List<MediaItem>();for(int i=0;i<normalized.Count;i++){var m=normalized[i];if(m.Composition=="4 Cadrane → 1"&&i+3<normalized.Count){var outc=Path.Combine(dir,$"carousel4_{i:0000}.mp4");var dur=Math.Max(4.2,new[]{normalized[i].Duration,normalized[i+1].Duration,normalized[i+2].Duration,normalized[i+3].Duration}.Min());var graph=CompositionRenderEngine.BuildFourToOne(dur);Ffmpeg($"-y -i \"{normalized[i].Path}\" -i \"{normalized[i+1].Path}\" -i \"{normalized[i+2].Path}\" -i \"{normalized[i+3].Path}\" -filter_complex \"{graph}\" -map \"[outv]\" -an -c:v libx264 -preset medium -pix_fmt yuv420p \"{outc}\"");sequence.Add(new MediaItem{Path=outc,Type="Video",Duration=dur,Transition=m.Transition,TransitionDuration=m.TransitionDuration});i+=3;}else if(m.Composition!="Full Frame"&&i+1<normalized.Count){var second=normalized[i+1];var outc=Path.Combine(dir,$"comp{i:0000}.mp4");var dur=Math.Max(1.2,Math.Min(m.Duration,second.Duration));var graph=CompositionRenderEngine.BuildTwoPlan(m.Composition,dur);Ffmpeg($"-y -i \"{m.Path}\" -i \"{second.Path}\" -filter_complex \"{graph}\" -map \"[outv]\" -an -c:v libx264 -preset medium -pix_fmt yuv420p \"{outc}\"");sequence.Add(new MediaItem{Path=outc,Type="Video",Duration=dur,Transition=m.Transition,TransitionDuration=m.TransitionDuration});i++;}else sequence.Add(m);}
 var visual=Path.Combine(dir,"visual.mp4");if(sequence.Count==1)File.Copy(sequence[0].Path,visual,true);else{var inputs=string.Join(" ",sequence.Select(x=>$"-i \"{x.Path}\""));var graph=SlideshowRenderEngine.BuildPhotoFilter(sequence);Ffmpeg($"-y {inputs} -filter_complex \"{graph}\" -map \"[outv]\" -an -c:v libx264 -preset medium -pix_fmt yuv420p \"{visual}\"");}if(music==null)File.Copy(visual,dest,true);else Ffmpeg($"-y -i \"{visual}\" -stream_loop -1 -i \"{music}\" -map 0:v -map 1:a -c:v copy -c:a aac -b:a 256k -shortest \"{dest}\"");}finally{try{Directory.Delete(dir,true);}catch{}}}
 void Normalize(MediaItem m,string c){var vf="scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black,fps=30,format=yuv420p";if(m.Type=="Foto")Ffmpeg($"-y -loop 1 -t {F(m.Duration)} -i \"{m.Path}\" -vf \"{vf}\" -an -c:v libx264 -preset medium \"{c}\"");else Ffmpeg($"-y -ss {F(m.TrimIn)} -i \"{m.Path}\" -t {F(m.Duration)} -vf \"{vf}\" -an -c:v libx264 -preset medium \"{c}\"");}
 static string F(double n)=>n.ToString("0.###",CultureInfo.InvariantCulture);static void Ffmpeg(string args){var t=Run("ffmpeg.exe",args,out var c);if(c!=0)throw new Exception("FFmpeg a oprit exportul.\n\n"+(t.Length>1800?t[^1800..]:t));}
 static string Run(string exe,string args,out int code){var path=Path.Combine(AppContext.BaseDirectory,"Tools",exe);if(!File.Exists(path))throw new FileNotFoundException("Lipsește "+exe,path);using var p=new Process();p.StartInfo=new ProcessStartInfo(path,args){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};var sb=new StringBuilder();p.OutputDataReceived+=(_,e)=>{if(e.Data!=null)lock(sb)sb.AppendLine(e.Data);};p.ErrorDataReceived+=(_,e)=>{if(e.Data!=null)lock(sb)sb.AppendLine(e.Data);};p.Start();p.BeginOutputReadLine();p.BeginErrorReadLine();p.WaitForExit();code=p.ExitCode;lock(sb)return sb.ToString();}
 void Window_PreviewDragOver(object s,DragEventArgs e){e.Effects=e.Data.GetDataPresent(DataFormats.FileDrop)?DragDropEffects.Copy:DragDropEffects.None;e.Handled=true;}async void Window_Drop(object s,DragEventArgs e){if(e.Data.GetData(DataFormats.FileDrop)is string[] files)await ImportFilesAsync(files);}
}